// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7k1wRkcDcwdEnKJFqRCvcvNsDgP-d2I4',
    appId: '1:987814337438:web:1263f19297bed2dea5d48f',
    messagingSenderId: '987814337438',
    projectId: 'avo-push',
    authDomain: 'avo-push.firebaseapp.com',
    storageBucket: 'avo-push.appspot.com',
    measurementId: 'G-3RTW8QB50T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxDEbx5r-dbBkEfkff2G4SySjOPkOGrRc',
    appId: '1:987814337438:android:629b29c2a20627aca5d48f',
    messagingSenderId: '987814337438',
    projectId: 'avo-push',
    storageBucket: 'avo-push.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaJKKy-_nOQEu7uztA4ysUpZ2orGuTyPs',
    appId: '1:987814337438:ios:e47a0eb4ad074751a5d48f',
    messagingSenderId: '987814337438',
    projectId: 'avo-push',
    storageBucket: 'avo-push.appspot.com',
    iosClientId: '987814337438-iqtood4aip4olqaaadji3jat238fah5k.apps.googleusercontent.com',
    iosBundleId: 'AVOTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaJKKy-_nOQEu7uztA4ysUpZ2orGuTyPs',
    appId: '1:987814337438:ios:ab2403eb0e270688a5d48f',
    messagingSenderId: '987814337438',
    projectId: 'avo-push',
    storageBucket: 'avo-push.appspot.com',
    iosClientId: '987814337438-is0mk75nf6g9vm5eigeoilgt27fmkn25.apps.googleusercontent.com',
    iosBundleId: 'com.example.avoFront',
  );
}
